version: '3.8'

services:
  mysql:
    build: .
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./config/sql/:/docker-entrypoint-initdb.d/

volumes:
  mysql_dev_data:
